### ISSUE TITLE
Chore: rename packages

### ISSUE THREAD

**Issue by fabianschu** [Curve-Labs/ie-bacalhau#7]
**Status quo**
- there are two packages: on-chain and off-chain
- this separation isn't optimal since we have essentially three components: the docker container, the hardhat project to interact with contracts, and the ceramic logic

**Acceptance Criteria**

- [ ] rename `/off-chain` to `/docker`
- [ ] rename `/on-chain` to `/hardhat`
- [ ] name the new package `/ceramic`

**Comment by Zitzak** [comment]
Closing this issue because the decision was made to rename:
- `/ceramics/ -> /datamodel/`
- keep `/on-chain/` as is for now
- `/off-chain/ -> /bacalhau/`
